# Generated by Django 4.0.5 on 2022-06-30 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_alter_composition_discription_and_more'),
        ('anime', '0002_animeseasons_animeseries_animevideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Anime Season Number')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='anime', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='animeseasons',
            name='anime',
        ),
        migrations.AlterField(
            model_name='anime',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.composition', verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='description',
            field=models.TextField(verbose_name='Description of the Series'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Series Name'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Anime Series Number'),
        ),
        migrations.DeleteModel(
            name='AnimeVideos',
        ),
        migrations.AddField(
            model_name='animevideo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animeseries', verbose_name='Anime Series'),
        ),
        migrations.AddField(
            model_name='animeseason',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Anime'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animeseason', verbose_name='Anime Season'),
        ),
        migrations.DeleteModel(
            name='AnimeSeasons',
        ),
    ]
