# Generated by Django 4.0.5 on 2022-07-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_animeseason_animevideo_remove_animeseasons_anime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name_plural': 'Anime'},
        ),
        migrations.AlterField(
            model_name='animeseason',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_seasons', to='anime.anime', verbose_name='Anime'),
        ),
    ]
