# Generated by Django 4.0.5 on 2022-07-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_options_alter_animeseason_anime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeseason',
            options={'verbose_name_plural': 'Anime Season'},
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_series', to='anime.animeseason', verbose_name='Anime Season'),
        ),
    ]
