# Generated by Django 4.0.5 on 2022-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_animeseason_options_alter_animeseries_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeseries',
            options={'verbose_name_plural': 'Anime Series'},
        ),
    ]
