# Generated by Django 4.0.5 on 2022-07-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_animeseries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animevideo',
            options={'verbose_name_plural': 'Anime Video'},
        ),
        migrations.RemoveField(
            model_name='animeseries',
            name='name',
        ),
    ]
