# Generated by Django 4.0.5 on 2022-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_animeseries_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeseries',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Series Name'),
        ),
    ]
