# Generated by Django 4.0.5 on 2022-07-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_animeseries_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Онгоинг'), (2, 'Вышел'), (3, 'Анонс')], null=True, verbose_name='anime release status'),
        ),
    ]
