# Generated by Django 4.0.5 on 2022-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ongoing'), (2, 'Came Out'), (3, 'Announcement')], null=True, verbose_name='anime release status'),
        ),
    ]
