# Generated by Django 4.0.5 on 2022-07-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0004_alter_composition_options'),
        ('anime', '0011_alter_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='compositions.composition', verbose_name='Composition'),
        ),
    ]
