# Generated by Django 4.0.5 on 2022-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_description_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='rang',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student of the academy'), (2, 'Genin'), (3, 'Chuunin'), (4, 'Special Jounin'), (5, 'JOUNIN'), (6, 'Kage')], default=2, verbose_name='User Rang'),
        ),
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(to='users.achievement'),
        ),
    ]
