# Generated by Django 4.0.5 on 2022-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('users', '0003_achievement_remove_user_description_remove_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AlterField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(to='achievements.achievement'),
        ),
    ]
