# Generated by Django 4.0.5 on 2022-07-14 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_achievement_alter_user_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='-', upload_to='', verbose_name='Avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rang',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student of the academy'), (2, 'Genin'), (3, 'Chuunin'), (4, 'Special Jounin'), (5, 'JOUNIN'), (6, 'Kage')], default=1, verbose_name='User Rang'),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='', verbose_name='User Avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Avatar',
            },
        ),
    ]
