# Generated by Django 4.0.5 on 2022-07-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_alter_user_rang_useravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
