# Generated by Django 4.0.5 on 2022-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0003_ranobechapter_ranobetext_ranobevolume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranobe',
            options={'verbose_name_plural': 'Ranobe'},
        ),
    ]
