# Generated by Django 4.0.5 on 2022-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0004_alter_ranobe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranobevolume',
            options={'verbose_name_plural': 'RanobeVolume'},
        ),
        migrations.RemoveField(
            model_name='ranobevolume',
            name='name',
        ),
        migrations.AddField(
            model_name='ranobevolume',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Volume Number'),
        ),
    ]
