# Generated by Django 4.0.5 on 2022-07-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0005_alter_ranobevolume_options_remove_ranobevolume_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranobevolume',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Volume Number'),
        ),
        migrations.AlterField(
            model_name='ranobevolume',
            name='ranobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranobe_volumes', to='ranobe.ranobe', verbose_name='Ranobe'),
        ),
    ]
