# Generated by Django 4.0.5 on 2022-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0006_alter_ranobevolume_number_alter_ranobevolume_ranobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranobe',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Продолжается'), (2, 'Заморожен'), (3, 'Завершен'), (4, 'Заброшен')], null=True, verbose_name='Transfer Status'),
        ),
    ]
