# Generated by Django 4.0.5 on 2022-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0008_alter_ranobechapter_options_alter_ranobetext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranobevolume',
            name='name',
            field=models.CharField(default='-', max_length=120, verbose_name='Volume Name'),
            preserve_default=False,
        ),
    ]
