# Generated by Django 4.0.5 on 2022-06-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('translation', models.CharField(max_length=120)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangachapters')),
            ],
        ),
        migrations.AddField(
            model_name='mangachapters',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangavolumes'),
        ),
    ]
