# Generated by Django 4.0.5 on 2022-06-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_alter_composition_discription_and_more'),
        ('manga', '0002_mangachapters_mangavolumes_mangaimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Chapter Number')),
                ('name', models.CharField(max_length=120, verbose_name='Chapter Title')),
                ('description', models.TextField(verbose_name='Chapter Description')),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Volume Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='mangachapters',
            name='volume',
        ),
        migrations.AlterField(
            model_name='manga',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.composition', verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='mangaimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mangaimages',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Page of Manga Chapter'),
        ),
        migrations.AlterField(
            model_name='mangaimages',
            name='translation',
            field=models.CharField(max_length=120, verbose_name='Translated by: '),
        ),
        migrations.DeleteModel(
            name='MangaVolumes',
        ),
        migrations.AddField(
            model_name='mangavolume',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga', verbose_name='Manga'),
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangavolume', verbose_name='Manga Volume'),
        ),
        migrations.AlterField(
            model_name='mangaimages',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangachapter', verbose_name='Manga Chapter'),
        ),
        migrations.DeleteModel(
            name='MangaChapters',
        ),
    ]
