# Generated by Django 4.0.5 on 2022-07-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_mangachapter_mangavolume_remove_mangachapters_volume_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MangaImages',
            new_name='MangaImage',
        ),
    ]
