# Generated by Django 4.0.5 on 2022-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_rename_mangaimages_mangaimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name_plural': 'Manga'},
        ),
    ]
