# Generated by Django 4.0.5 on 2022-07-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapter',
            options={'verbose_name_plural': 'Manga Chapter'},
        ),
        migrations.AlterModelOptions(
            name='mangaimage',
            options={'verbose_name_plural': 'Mango Image'},
        ),
        migrations.AlterModelOptions(
            name='mangavolume',
            options={'verbose_name_plural': 'Manga Volume'},
        ),
        migrations.RemoveField(
            model_name='mangachapter',
            name='name',
        ),
        migrations.AlterField(
            model_name='mangachapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_chapters', to='manga.mangavolume', verbose_name='Manga Volume'),
        ),
        migrations.AlterField(
            model_name='mangavolume',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_volumes', to='manga.manga', verbose_name='Manga'),
        ),
    ]
