# Generated by Django 4.0.5 on 2022-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_mangachapter_options_alter_mangaimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapter',
            name='name',
            field=models.CharField(default=False, max_length=120, verbose_name='Chapter Title'),
        ),
    ]
