# Generated by Django 4.0.5 on 2022-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_remove_mangaimage_translation_manga_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='translation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Продолжается'), (2, 'Заморожен'), (3, 'Завершен'), (4, 'Заброшен')], null=True, verbose_name='Translated status: '),
        ),
    ]
