# Generated by Django 4.0.5 on 2022-07-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_alter_composition_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='discription',
            new_name='description',
        ),
    ]
